# Copyright (c) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Auto-generate C++ encoding translator functions for cross-ISA DBT.

For each (src_ISA, dst_ISA) pair, emits C++ functions that translate
instructions by decoding fields from the source ISA's machine_insts.h
bitfield struct and re-encoding with the target ISA's generated builders.
Decoder-only alternate target encodings, which do not yet have standalone
builders, retain the existing MachineInst serialization path.

Fields are classified as:
- COPY:   same name, same width -- bitfield value is copied directly.
- REMAP:  same concept, different XML name -- copied under the new name.
- DROP:   present on source, absent on target -- field is not written.
- INSERT: absent on source, present on target -- set to a default value.

Usage::

    from amdisa import Parser
    from amdisa.isa_profile import Cdna4Profile, Rdna4Profile
    from amdisa.encoding_translator_codegen import generate_encoding_translators

    cdna4 = Parser('amdgpu_isa_cdna4.xml', Cdna4Profile()).parse()
    rdna4 = Parser('amdgpu_isa_rdna4.xml', Rdna4Profile()).parse()
    generate_encoding_translators(cdna4, rdna4, 'cdna4', 'rdna4', 'output/')
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from amdisa.codegen.config import CodegenConfig


def _clang_format(path: Path) -> None:
    """Run clang-format -i on path. Silent no-op if clang-format isn't on PATH.

    The codegen emits 4-space indented bodies; project style is 2-space (set
    by the .clang-format at the rocjitsu root). Always running clang-format
    here keeps regenerated files diff-clean even when callers forget to run
    it manually.
    """
    exe = shutil.which('clang-format')
    if not exe:
        print(
            'warning: clang-format not found; emitted files may need manual '
            'formatting',
            file=sys.stderr,
        )
        return
    subprocess.run([exe, '-i', str(path)], check=True)


if TYPE_CHECKING:
    from amdisa.gpuisa import InstEncoding, IsaSpec

# ---------------------------------------------------------------------------
# Copyright header for generated files
# ---------------------------------------------------------------------------

_COPYRIGHT = """\
// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
"""

# ---------------------------------------------------------------------------
# Field rename map: XML field names that differ but are semantically identical
# ---------------------------------------------------------------------------

FIELD_RENAMES: dict[str, str] = {
    'op_sel': 'opsel',
    'op_sel_hi': 'opsel_hi',
    'op_sel_hi_2': 'opsel_hi_2',
    'offset': 'ioffset',  # SMEM, MUBUF, FLAT offset → RDNA4 ioffset
    'data': 'vsrc',  # FLAT store source field
    'srsrc': 'rsrc',  # MUBUF buffer resource → VBUFFER rsrc (5b → 9b)
    'addr': 'vaddr',  # FLAT address register → VGLOBAL vaddr
    'data0': 'data0',  # DS data fields — same name, keep explicit
    'data1': 'data1',
}

# Reverse map for looking up src->dst in either direction
_REVERSE_RENAMES: dict[str, str] = {v: k for k, v in FIELD_RENAMES.items()}

# ---------------------------------------------------------------------------
# Encoding format pairing: which source encoding maps to which target
# ---------------------------------------------------------------------------

# Maps (src_enc_name -> dst_enc_name) for CDNA4 -> RDNA4. RDNA4 introduced
# new dedicated V-prefix encodings (VFLAT/VGLOBAL/VSCRATCH/VDS/VBUFFER) for
# memory and LDS ops; CDNA's FLAT-family encodings translate into them.
_CDNA4_TO_RDNA4_ENC_MAP: dict[str, str] = {
    'ENC_SOP1': 'ENC_SOP1',
    'ENC_SOP2': 'ENC_SOP2',
    'ENC_SOPC': 'ENC_SOPC',
    'ENC_SOPK': 'ENC_SOPK',
    'ENC_SOPP': 'ENC_SOPP',
    'ENC_SMEM': 'ENC_SMEM',
    'ENC_VOP1': 'ENC_VOP1',
    'ENC_VOP2': 'ENC_VOP2',
    'ENC_VOPC': 'ENC_VOPC',
    'ENC_VOP3': 'ENC_VOP3',
    'ENC_VOP3P': 'ENC_VOP3P',
    'ENC_DS': 'ENC_VDS',
    'ENC_MUBUF': 'ENC_VBUFFER',
    'ENC_FLAT': 'ENC_VFLAT',
    'ENC_FLAT_GLBL': 'ENC_VGLOBAL',
    'ENC_FLAT_SCRATCH': 'ENC_VSCRATCH',
    'VOP3_SDST_ENC': 'VOP3_SDST_ENC',
}

# Maps (src_enc_name -> dst_enc_name) for CDNA4 -> RDNA3. RDNA3 retains the
# original FLAT-family encodings (no V-prefix) but renames CDNA's FLAT_GLBL
# to FLAT_GLOBAL. Bit positions of fields differ within these encodings (e.g.
# coherency bits, seg position) but C++ bitfield-to-bitfield assignment in
# the auto-generated encoder handles the position differences automatically.
_CDNA4_TO_RDNA3_ENC_MAP: dict[str, str] = {
    'ENC_SOP1': 'ENC_SOP1',
    'ENC_SOP2': 'ENC_SOP2',
    'ENC_SOPC': 'ENC_SOPC',
    'ENC_SOPK': 'ENC_SOPK',
    'ENC_SOPP': 'ENC_SOPP',
    'ENC_SMEM': 'ENC_SMEM',
    'ENC_VOP1': 'ENC_VOP1',
    'ENC_VOP2': 'ENC_VOP2',
    'ENC_VOPC': 'ENC_VOPC',
    'ENC_VOP3': 'ENC_VOP3',
    'ENC_VOP3P': 'ENC_VOP3P',
    'ENC_DS': 'ENC_DS',
    'ENC_MUBUF': 'ENC_MUBUF',
    'ENC_FLAT': 'ENC_FLAT',
    'ENC_FLAT_GLBL': 'ENC_FLAT_GLOBAL',
    'ENC_FLAT_SCRATCH': 'ENC_FLAT_SCRATCH',
    'VOP3_SDST_ENC': 'VOP3_SDST_ENC',
}

# Maps (src_enc_name -> dst_enc_name) for CDNA4 -> CDNA3. These are adjacent
# CDNA generations, so the encoding-family names remain the same; field
# positions and opcode substitutions are still handled through the generated
# decode/encode functions and legalization table.
_CDNA4_TO_CDNA3_ENC_MAP: dict[str, str] = {
    'ENC_SOP1': 'ENC_SOP1',
    'ENC_SOP2': 'ENC_SOP2',
    'ENC_SOPC': 'ENC_SOPC',
    'ENC_SOPK': 'ENC_SOPK',
    'ENC_SOPP': 'ENC_SOPP',
    'ENC_SMEM': 'ENC_SMEM',
    'ENC_VOP1': 'ENC_VOP1',
    'ENC_VOP2': 'ENC_VOP2',
    'ENC_VOPC': 'ENC_VOPC',
    'ENC_VOP3': 'ENC_VOP3',
    'ENC_VOP3P': 'ENC_VOP3P',
    'ENC_DS': 'ENC_DS',
    'ENC_MTBUF': 'ENC_MTBUF',
    'ENC_MUBUF': 'ENC_MUBUF',
    'ENC_FLAT': 'ENC_FLAT',
    'ENC_FLAT_GLBL': 'ENC_FLAT_GLBL',
    'ENC_FLAT_SCRATCH': 'ENC_FLAT_SCRATCH',
    'VOP3_SDST_ENC': 'VOP3_SDST_ENC',
}

# Lookup the right per-pair enc_map. New target ISAs are added by appending
# entries here plus a corresponding _CDNA4_TO_<DST>_ENC_MAP definition above.
_PAIR_ENC_MAPS: dict[tuple[str, str], dict[str, str]] = {
    ('cdna4', 'cdna3'): _CDNA4_TO_CDNA3_ENC_MAP,
    ('cdna4', 'rdna4'): _CDNA4_TO_RDNA4_ENC_MAP,
    ('cdna4', 'rdna3'): _CDNA4_TO_RDNA3_ENC_MAP,
}

# ---------------------------------------------------------------------------
# Coherency remap: encodings whose memory-ordering fields require semantic
# translation (GFX940 sc0/sc1/nt -> GFX12 scope/th)
# ---------------------------------------------------------------------------

_COHERENCY_REMAP_ENCODINGS = frozenset(
    {
        'ENC_MUBUF',
        'ENC_FLAT',
        'ENC_FLAT_GLBL',
        'ENC_FLAT_SCRATCH',
    }
)

_GLC_REMAP_ENCODINGS = frozenset(
    {
        'ENC_SMEM',
    }
)

# Fields that participate in coherency remapping (source side)
_COHERENCY_SRC_FIELDS = frozenset({'sc0', 'sc1', 'nt', 'glc'})

# Fields that participate in coherency remapping (target side)
_COHERENCY_DST_FIELDS = frozenset({'scope', 'th'})

# ---------------------------------------------------------------------------
# Field classification
# ---------------------------------------------------------------------------


@dataclass
class FieldMapping:
    """Describes how a single field maps from source to target encoding."""

    kind: str  # 'copy', 'remap', 'drop', 'insert', 'coherency'
    src_name: str  # field name on source ('' for insert)
    dst_name: str  # field name on target ('' for drop)
    src_bits: int  # bit width on source
    dst_bits: int  # bit width on target
    comment: str = ''  # human-readable explanation


@dataclass
class EncodingTranslation:
    """Complete translation recipe for one encoding pair."""

    src_enc_name: str
    dst_enc_name: str
    src_struct: str  # C++ struct name on source
    dst_struct: str  # C++ struct name on target
    src_bit_cnt: int
    dst_bit_cnt: int
    mappings: list[FieldMapping] = field(default_factory=list)
    has_coherency_remap: bool = False
    has_glc_remap: bool = False
    src_dt_index: int = 0  # primary decode table index (for dispatch)
    src_enc_field_bit_cnt: int = 9  # encoding field width in bits
    dst_enc_field_val: int = 0  # actual encoding bitfield value (for dst.encoding)
    dst_has_builder: bool = False  # target is emitted by gen_instruction_builders


# ---------------------------------------------------------------------------
# Struct name derivation (matches codegen.py convention)
# ---------------------------------------------------------------------------


def _struct_name(enc_name: str) -> str:
    """Derive the C++ MachineInst struct name from an encoding name.

    Examples:
        ENC_SOP1 -> Sop1MachineInst
        ENC_VOP3P -> Vop3pMachineInst
        ENC_FLAT_GLBL -> FlatGlblMachineInst
        VOP3_SDST_ENC -> Vop3SdstEncMachineInst
        ENC_VDS -> VdsMachineInst
        ENC_VBUFFER -> VbufferMachineInst
        ENC_VFLAT -> VflatMachineInst
    """
    parts = enc_name.split('_')
    if parts[0] == 'ENC':
        parts = parts[1:]
    return ''.join(p.capitalize() for p in parts) + 'MachineInst'


def _builder_fields_name(enc_name: str) -> str:
    """Derive the C++ generated-builder field structure name."""
    return _struct_name(enc_name).replace('MachineInst', 'BuilderFields')


def _builder_function_name(enc_name: str) -> str:
    """Derive the generated format-builder function name."""
    if enc_name.startswith('ENC_'):
        enc_name = enc_name[len('ENC_') :]
    return f'build_{enc_name.lower()}'


def _dt_index(enc: InstEncoding, spec: IsaSpec) -> int:
    """Extract the primary decode table index for the encoding.

    The primary decode table index encodes the ``encoding`` field value
    shifted left by the don't-care bits. We extract it from the first
    non-negative primary_dt_ptrs entry.  Used for dispatch constants.
    """
    if enc.primary_dt_ptrs is None:
        # Alternate encodings (FLAT_GLBL, etc.) share the parent's DT.
        parent_name = spec.profile.derive_parent_enc_name(enc.enc_name)
        if parent_name in spec.encoding_map:
            parent_enc = spec.encoding_map[parent_name]
            return _dt_index(parent_enc, spec)
        return 0
    for ptr in enc.primary_dt_ptrs:
        if ptr != -1:
            return ptr
    return 0


def _enc_field_value(enc: InstEncoding, spec: IsaSpec) -> int:
    """Extract the actual value of the 'encoding' bitfield constant.

    This is the value written into ``dst.encoding = <value>`` in the
    generated translator functions. Computed as:

        dt_index >> (max_enc_bits - enc_field_bit_cnt)

    Because the DT index is ``enc_value << don't_care_bits``.
    """
    dt_idx = _dt_index(enc, spec)
    max_enc_bits = spec.profile.max_enc_bits
    dont_care = max_enc_bits - enc.enc_field_bit_cnt
    return dt_idx >> dont_care


# ---------------------------------------------------------------------------
# Field matching logic
# ---------------------------------------------------------------------------


def _is_pad_field(name: str) -> bool:
    """True if this is a synthesized padding field."""
    return name.startswith('pad_')


def _uses_rdna_null_sgpr_sentinel(dst_name: str) -> bool:
    """True when the destination ISA uses RDNA's 0x7c null scalar-register sentinel.

    CDNA encodings use 0x7f for null 7-bit scalar operands and SMEM has an
    explicit ``soffset_en`` bit to disable scalar offsets. Rewriting those
    fields while translating CDNA4->CDNA3 corrupts otherwise bit-compatible
    instructions such as kernarg ``s_load_*`` loads.
    """
    return dst_name.startswith('rdna')


def _classify_fields(
    src_enc: InstEncoding,
    dst_enc: InstEncoding,
    src_enc_name: str,
    has_coherency_remap: bool,
    has_glc_remap: bool,
) -> list[FieldMapping]:
    """Classify each field in the src/dst encoding pair."""

    src_fields = {f.name: f for f in src_enc.ucode_fields if not _is_pad_field(f.name)}
    dst_fields = {f.name: f for f in dst_enc.ucode_fields if not _is_pad_field(f.name)}

    mappings: list[FieldMapping] = []
    matched_dst: set[str] = set()

    for sname, sf in src_fields.items():
        # Skip encoding field -- set separately with the target constant
        if sname == 'encoding':
            continue

        # Coherency fields handled specially
        if has_coherency_remap and sname in _COHERENCY_SRC_FIELDS:
            mappings.append(
                FieldMapping(
                    'coherency',
                    sname,
                    '',
                    sf.bit_cnt,
                    0,
                    f'coherency remap: {sname} -> scope/th',
                )
            )
            continue

        if has_glc_remap and sname == 'glc':
            mappings.append(
                FieldMapping(
                    'glc_remap',
                    sname,
                    '',
                    sf.bit_cnt,
                    0,
                    f'GLC remap: glc -> scope/th',
                )
            )
            continue

        # Direct match (same name)
        if sname in dst_fields:
            df = dst_fields[sname]
            matched_dst.add(sname)
            mappings.append(
                FieldMapping(
                    'copy',
                    sname,
                    sname,
                    sf.bit_cnt,
                    df.bit_cnt,
                    f'COPY {sname} ({sf.bit_cnt}b -> {df.bit_cnt}b)',
                )
            )
            continue

        # Rename match
        renamed = FIELD_RENAMES.get(sname)
        if renamed and renamed in dst_fields:
            df = dst_fields[renamed]
            matched_dst.add(renamed)
            mappings.append(
                FieldMapping(
                    'remap',
                    sname,
                    renamed,
                    sf.bit_cnt,
                    df.bit_cnt,
                    f'REMAP {sname} -> {renamed} ({sf.bit_cnt}b -> {df.bit_cnt}b)',
                )
            )
            continue

        # Reverse rename match
        rev_renamed = _REVERSE_RENAMES.get(sname)
        if rev_renamed and rev_renamed in dst_fields:
            df = dst_fields[rev_renamed]
            matched_dst.add(rev_renamed)
            mappings.append(
                FieldMapping(
                    'remap',
                    sname,
                    rev_renamed,
                    sf.bit_cnt,
                    df.bit_cnt,
                    f'REMAP {sname} -> {rev_renamed} ({sf.bit_cnt}b -> {df.bit_cnt}b)',
                )
            )
            continue

        # No match -> DROP
        mappings.append(
            FieldMapping(
                'drop',
                sname,
                '',
                sf.bit_cnt,
                0,
                f'DROP {sname} ({sf.bit_cnt}b) -- not present on target',
            )
        )

    # INSERT: target fields not matched by any source field
    for dname, df in dst_fields.items():
        if dname == 'encoding':
            continue
        if dname in matched_dst:
            continue
        # Coherency destination fields are handled by the coherency remap
        if (has_coherency_remap or has_glc_remap) and dname in _COHERENCY_DST_FIELDS:
            continue
        mappings.append(
            FieldMapping(
                'insert',
                '',
                dname,
                0,
                df.bit_cnt,
                f'INSERT {dname} ({df.bit_cnt}b) -- new on target, default 0',
            )
        )

    return mappings


# ---------------------------------------------------------------------------
# Neutral intermediate field structs + decode/encode emission
# ---------------------------------------------------------------------------


def _fields_struct_name(enc_name: str) -> str:
    parts = enc_name.split('_')
    if parts[0] == 'ENC':
        parts = parts[1:]
    return ''.join(p.capitalize() for p in parts) + 'Fields'


def _all_field_names_from_encodings(encodings):
    """Collect the union of all non-padding, non-encoding field names across
    multiple ISAs' encodings for the same format.

    Returned sorted alphabetically so the emitted struct layout is stable
    across ISA argument orderings. Field order in these structs is
    cosmetic (every read/write in the generated code is by name) but a
    deterministic order avoids gratuitous diff churn on regeneration.
    """
    seen = set()
    for enc in encodings:
        for f in enc.ucode_fields:
            if f.name.startswith('pad_') or f.name == 'encoding':
                continue
            seen.add(FIELD_RENAMES.get(f.name, f.name))
    return sorted(seen)


def _emit_fields_struct(enc_name, field_names):
    sname = _fields_struct_name(enc_name)
    lines = [f'struct {sname} {{']
    for name in field_names:
        lines.append(f'    uint32_t {name};')
    lines += ['};', '']
    return lines


def generate_encoding_fields(all_specs, output_dir):
    """Generate encoding_fields.h with neutral field structs from ALL ISAs.

    The field structs contain the union of all fields across all ISA
    variants of each encoding format, ensuring they are truly universal.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Collect all encoding format names across all ISAs, including alternate
    # encodings (FLAT_GLBL, FLAT_SCRATCH) that share a parent's decode table
    # but have distinct field layouts.
    all_enc_names = set()
    for _, spec, _ in all_specs:
        for enc in spec.inst_encodings:
            if enc.insts:
                all_enc_names.add(enc.enc_name)
        for enc_name in spec.encoding_map:
            all_enc_names.add(enc_name)
    # Also include all names referenced by any per-pair enc_map (so a struct
    # exists even if the encoding only appears as a translation target).
    for enc_map in _PAIR_ENC_MAPS.values():
        for src, dst in enc_map.items():
            all_enc_names.add(src)
            all_enc_names.add(dst)

    # For each encoding format, collect field names from all ISAs that have it
    # and capture a representative dt_index (the encoding-format ID is universal
    # across ISA variants - any spec that defines the encoding gives the same
    # value).
    enc_fields: dict[str, list[str]] = {}
    enc_dt_index: dict[str, int] = {}
    for enc_name in sorted(all_enc_names):
        encodings = []
        rep_spec = None
        for _, spec, _ in all_specs:
            if enc_name in spec.encoding_map:
                encodings.append(spec.encoding_map[enc_name])
                if rep_spec is None:
                    rep_spec = spec
        if encodings:
            enc_fields[enc_name] = _all_field_names_from_encodings(encodings)
            enc_dt_index[enc_name] = _dt_index(encodings[0], rep_spec)

    lines = [
        _COPYRIGHT,
        '',
        '#pragma once',
        '',
        '#include <cstdint>',
        '',
        'namespace rocjitsu {',
        '',
    ]
    # Emit universal encoding-format ID constants once. Per-pair translator
    # headers reference these via #include "encoding_fields.h", so they MUST
    # NOT redefine them at namespace scope (ODR violation when more than one
    # per-pair header is included in the same translation unit).
    for enc_name in sorted(enc_dt_index):
        cn = enc_name.upper().replace('ENC_', '')
        lines.append(
            f'inline constexpr uint32_t kEnc_{cn} = 0x{enc_dt_index[enc_name]:X};'
        )
    lines.append('')
    for enc_name in sorted(enc_fields):
        lines.extend(_emit_fields_struct(enc_name, enc_fields[enc_name]))
    lines += ['}  // namespace rocjitsu', '']

    path = output_dir / 'encoding_fields.h'
    path.write_text('\n'.join(lines))
    _clang_format(path)

    print(
        f'Generated encoding_fields.h with {len(enc_fields)} field structs '
        f'from {len(all_specs)} ISAs',
        file=sys.stderr,
    )
    return str(path)


def _emit_decode_fn(trans, src_ns, src_name):
    base = trans.src_enc_name.lower().replace('enc_', '')
    fn = f'decode_{base}_{src_name}'
    fsname = _fields_struct_name(trans.src_enc_name)
    src_fmap = {
        f.name: f for f in [ff for ff in __import__('itertools').chain([], [])]
    }  # unused placeholder

    bit_cnt = trans.src_bit_cnt
    full_type = f'{src_ns}::{trans.src_struct}'

    lines = []
    if bit_cnt <= 32:
        params = 'uint32_t w0'
    elif bit_cnt == 64:
        params = 'uint32_t w0, uint32_t w1'
    else:
        params = 'uint32_t w0, uint32_t w1, uint32_t w2'

    lines.append(f'inline {fsname} {fn}({params}) {{')
    if bit_cnt <= 32:
        lines.append(f'    auto src = std::bit_cast<{full_type}>(w0);')
    else:
        n = bit_cnt // 32
        ws = ', '.join(f'w{i}' for i in range(n))
        lines.append(f'    {full_type} src{{}};')
        lines.append(f'    const uint32_t src_words[] = {{{ws}}};')
        lines.append(f'    std::memcpy(&src, src_words, sizeof(src));')

    lines.append(f'    {fsname} f{{}};')

    # Extract source fields into neutral struct
    src_enc_obj = None  # Will be passed separately
    for m in trans.mappings:
        if m.kind in ('coherency', 'glc_remap'):
            # Coherency source fields go into the neutral struct too
            lines.append(f'    f.{m.src_name} = src.{m.src_name};')
        elif m.kind in ('copy', 'remap'):
            canonical = FIELD_RENAMES.get(m.src_name, m.src_name)
            lines.append(f'    f.{canonical} = src.{m.src_name};')
        elif m.kind == 'drop':
            canonical = FIELD_RENAMES.get(m.src_name, m.src_name)
            lines.append(f'    f.{canonical} = src.{m.src_name};')
        # insert: nothing to decode from source

    lines.append(f'    return f;')
    lines.append(f'}}')
    lines.append('')
    return lines


def _emit_encode_fn(trans, dst_ns, dst_name):
    base = trans.src_enc_name.lower().replace('enc_', '')
    fn = f'encode_{base}_{dst_name}'
    fsname = _fields_struct_name(trans.src_enc_name)
    full_type = (
        f'{dst_ns}::{_builder_fields_name(trans.dst_enc_name)}'
        if trans.dst_has_builder
        else f'{dst_ns}::{trans.dst_struct}'
    )
    bit_cnt = trans.dst_bit_cnt

    lines = []
    lines.append(
        f'inline TranslationResult {fn}(const {fsname} &f, uint16_t dst_op) {{'
    )
    lines.append(f'    {full_type} dst{{}};')
    if not trans.dst_has_builder:
        lines.append(f'    dst.encoding = 0x{trans.dst_enc_field_val:X};')
        lines.append(f'    dst.op = dst_op;')

    # Coherency remap
    if trans.has_coherency_remap:
        lines.append(
            f'    auto coh = remap_gfx940_to_gfx12({{uint8_t(f.sc0), uint8_t(f.sc1), uint8_t(f.nt)}});'
        )
        lines.append(f'    dst.scope = coh.scope;')
        lines.append(f'    dst.th = coh.th;')
    elif trans.has_glc_remap:
        lines.append(f'    auto coh = remap_gfx9_to_gfx12({{uint8_t(f.glc)}});')
        lines.append(f'    dst.scope = coh.scope;')
        lines.append(f'    dst.th = coh.th;')

    # Pack fields from the neutral struct into the target. Every assignment is
    # masked to the destination width so generated encoders stay correct when a
    # source XML field is wider than its target bitfield or carries stale high
    # bits from a previous decode path.
    for m in trans.mappings:
        if m.kind == 'copy':
            if m.src_name == 'op':
                continue
            dst_n = m.dst_name or m.src_name
            canonical = FIELD_RENAMES.get(m.src_name, m.src_name)
            mask = (1 << m.dst_bits) - 1
            lines.append(f'    dst.{dst_n} = f.{canonical} & 0x{mask:X};')
        elif m.kind == 'remap':
            canonical = FIELD_RENAMES.get(m.src_name, m.src_name)
            mask = (1 << m.dst_bits) - 1
            lines.append(f'    dst.{m.dst_name} = f.{canonical} & 0x{mask:X};')
        elif m.kind == 'insert':
            lines.append(f'    dst.{m.dst_name} = 0;')
        # drop and coherency: nothing to encode

    # Remap null register sentinels only when translating into RDNA encodings:
    # CDNA uses 0x7F (7-bit max), while RDNA uses 0x7C. CDNA SMEM also has an
    # explicit soffset_en bit; when the destination is another CDNA ISA, that
    # bit must keep carrying the disabled-offset state without changing soffset.
    if _uses_rdna_null_sgpr_sentinel(dst_name):
        if any(m.src_name == 'saddr' or m.dst_name == 'saddr' for m in trans.mappings):
            lines.append('    if (dst.saddr == 0x7F) dst.saddr = 0x7C;')
        if any(
            m.src_name == 'soffset' or m.dst_name == 'soffset' for m in trans.mappings
        ):
            lines.append('    if (dst.soffset == 0x7F) dst.soffset = 0x7C;')
            # CDNA SMEM uses soffset_en=0 to disable scalar offset. RDNA uses soffset=0x7C (null).
            if any(m.src_name == 'soffset_en' for m in trans.mappings):
                lines.append('    if (f.soffset_en == 0) dst.soffset = 0x7C;')

    # Builders are the canonical target-layout encoder. Alternate decoder-only
    # formats do not have builders yet because their selector conditions are
    # not represented by a single fixed encoding field; keep their generated
    # MachineInst path until selector-aware builders are available.
    if trans.dst_has_builder:
        builder = _builder_function_name(trans.dst_enc_name)
        n = (bit_cnt + 31) // 32
        lines.append(f'    const auto words = {dst_ns}::{builder}(dst_op, dst);')
        lines.append(f'    TranslationResult r{{}};')
        lines.append(f'    r.word_count = uint8_t{{{n}}};')
        for word in range(n):
            lines.append(f'    r.words[{word}] = words[{word}];')
        lines.append(f'    return r;')
    elif bit_cnt <= 32:
        lines.append(
            f'    return TranslationResult{{{{std::bit_cast<uint32_t>(dst), 0u, 0u}}, uint8_t{{1}}}};'
        )
    else:
        n = bit_cnt // 32
        lines.append(f'    TranslationResult r{{}};')
        lines.append(f'    r.word_count = uint8_t{{{n}}};')
        lines.append(f'    std::memcpy(r.words, &dst, sizeof(dst));')
        lines.append(f'    return r;')

    lines.append(f'}}')
    lines.append('')
    return lines


def _emit_dispatch(translations, src_name, dst_name, src_spec, dst_spec):
    val_groups: dict[int, list[EncodingTranslation]] = {}
    for t in translations:
        val_groups.setdefault(t.src_dt_index, []).append(t)

    # kEnc_* encoding-format IDs live in encoding_fields.h (universal across
    # ISA variants). Per-pair translator headers must not redefine them.
    lines = []

    fn = f'translate_encoding_{src_name}_to_{dst_name}'
    lines.append(f'inline TranslationResult {fn}(')
    lines.append(
        f'    uint32_t encoding_id, uint32_t w0, uint32_t w1, [[maybe_unused]] uint32_t w2,'
    )
    lines.append(f'    uint16_t dst_op) {{')
    # Build a priority-ordered lookup table: (enc_bits, base_val) sorted
    # by ascending bit count. Encodings with fewer bits must be tried first
    # because they mask away more bits. Used to normalize encoding_id.
    enc_entries = []
    seen_e: set[int] = set()
    for ev, grp in sorted(val_groups.items()):
        if ev not in seen_e:
            seen_e.add(ev)
            enc_entries.append((grp[0].src_enc_field_bit_cnt, ev))
    enc_entries.sort()

    # Emit a normalization chain: try each encoding format from narrowest
    # to widest, masking encoding_id to the format's field width and comparing.
    # No pre-normalization needed; handled in default: case below.

    lines.append(f'    switch (encoding_id) {{')

    seen_vals: set[int] = set()
    for enc_val, group in sorted(val_groups.items()):
        if enc_val in seen_vals:
            continue
        seen_vals.add(enc_val)
        first = group[0]
        cn = first.src_enc_name.upper().replace('ENC_', '')

        if len(group) == 1:
            t = group[0]
            base = t.src_enc_name.lower().replace('enc_', '')
            dec_fn = f'decode_{base}_{src_name}'
            enc_fn = f'encode_{base}_{dst_name}'
            args = (
                'w0'
                if t.src_bit_cnt <= 32
                else ('w0, w1' if t.src_bit_cnt == 64 else 'w0, w1, w2')
            )
            swap_compare_data = (
                t.src_enc_name in ('ENC_DS', 'ENC_VDS')
                and src_spec.profile.ds_compare_store_compare_first
                != dst_spec.profile.ds_compare_store_compare_first
            )
            if swap_compare_data:
                opcodes = sorted(
                    {
                        inst.opcode
                        for inst in src_spec.encoding_map[t.src_enc_name].insts
                        if inst.name.startswith(('DS_CMPST_', 'DS_CMPSTORE_'))
                    }
                )
                fields_type = _fields_struct_name(t.src_enc_name)
                lines.append(f'    case kEnc_{cn}: {{')
                lines.append(f'        {fields_type} fields = {dec_fn}({args});')
                lines.append('        switch (fields.op) {')
                for opcode in opcodes:
                    lines.append(f'        case {opcode}:')
                if opcodes:
                    lines.append('        {')
                    lines.append(
                        '            const uint32_t comparison = fields.data0;'
                    )
                    lines.append('            fields.data0 = fields.data1;')
                    lines.append('            fields.data1 = comparison;')
                    lines.append('            break;')
                    lines.append('        }')
                lines.append('        default: break;')
                lines.append('        }')
                lines.append(f'        return {enc_fn}(fields, dst_op);')
                lines.append('    }')
            else:
                lines.append(f'    case kEnc_{cn}:')
                lines.append(f'        return {enc_fn}({dec_fn}({args}), dst_op);')
        else:
            lines.append(f'    case kEnc_{cn}: {{')
            lines.append(f'        const uint8_t seg = (w0 >> 14) & 0x3;')
            lines.append(f'        switch (seg) {{')
            seg_map: dict[int, EncodingTranslation] = {}
            for t in group:
                u = t.src_enc_name.upper()
                if 'SCRATCH' in u:
                    seg_map[1] = t
                elif 'GLBL' in u or 'GLOBAL' in u:
                    seg_map[2] = t
                else:
                    seg_map[0] = t
            for sv in sorted(seg_map):
                t = seg_map[sv]
                base = t.src_enc_name.lower().replace('enc_', '')
                dec_fn = f'decode_{base}_{src_name}'
                enc_fn = f'encode_{base}_{dst_name}'
                args = (
                    'w0'
                    if t.src_bit_cnt <= 32
                    else ('w0, w1' if t.src_bit_cnt == 64 else 'w0, w1, w2')
                )
                lines.append(
                    f'        case {sv}: return {enc_fn}({dec_fn}({args}), dst_op);'
                )
            lines.append(f'        default: break;')
            lines.append(f'        }}')
            lines.append(f'        break;')
            lines.append(f'    }}')

    lines.append(f'    default:')
    lines.append(f'        break;')
    lines.append(f'    }}')

    # For formats with encoding fields narrower than 9 bits, the
    # 9-bit encoding_id has don't-care low bits. If no exact match,
    # try masking and retrying (one level, not recursive).
    need_norm = any(b < 9 for b, _ in enc_entries)
    if need_norm:
        # Build a static mapping from mask → base value, widest first.
        norm_entries_wide = sorted(
            [(b, v) for b, v in enc_entries if b < 9], key=lambda x: -x[0]
        )
        for bits, base_val in norm_entries_wide:
            mask = ((1 << bits) - 1) << (9 - bits)
            cn_n = val_groups[base_val][0].src_enc_name.upper().replace('ENC_', '')
            lines.append(f'    if ((encoding_id & 0x{mask:X}) == kEnc_{cn_n})')
            lines.append(f'        return {fn}(kEnc_{cn_n}, w0, w1, w2, dst_op);')

    lines.append(f'    return {{}};')
    lines.append(f'}}')
    lines.append('')
    return lines


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _extract_dt_indices(spec, enc_names):
    return {
        n: _dt_index(spec.encoding_map[n], spec)
        for n in enc_names
        if n in spec.encoding_map
    }


def _extract_enc_field_values(spec, enc_names):
    return {
        n: _enc_field_value(spec.encoding_map[n], spec)
        for n in enc_names
        if n in spec.encoding_map
    }


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def generate_encoding_translators(
    src_spec,
    dst_spec,
    src_name,
    dst_name,
    output_dir,
    config: CodegenConfig | None = None,
):
    config = config if config is not None else CodegenConfig()
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    enc_map = _PAIR_ENC_MAPS.get((src_name, dst_name))
    if enc_map is None:
        print(
            f'warning: no encoding map for ({src_name}, {dst_name}); '
            f'no translator will be generated',
            file=sys.stderr,
        )
        return []
    src_encs = [e.enc_name for e in src_spec.inst_encodings]
    dst_encs = [e.enc_name for e in dst_spec.inst_encodings]
    src_dts = _extract_dt_indices(src_spec, src_encs)
    dst_evs = _extract_enc_field_values(dst_spec, dst_encs)

    translations = []
    skipped = []
    for se, de in enc_map.items():
        if se not in src_spec.encoding_map:
            skipped.append(se)
            continue
        if de not in dst_spec.encoding_map:
            skipped.append(de)
            continue
        src_enc = src_spec.encoding_map[se]
        dst_enc = dst_spec.encoding_map[de]
        # The coherency remap targets GFX12-style scope/th fields. If the
        # destination encoding lacks those fields (e.g. RDNA3 SMEM with
        # glc/dlc), suppress the remap so the regular field-by-field copy
        # path handles glc/dlc directly.
        dst_field_names = {f.name for f in dst_enc.ucode_fields}
        dst_has_scope_th = 'scope' in dst_field_names and 'th' in dst_field_names
        has_coherency_remap = (se in _COHERENCY_REMAP_ENCODINGS) and dst_has_scope_th
        has_glc_remap = (se in _GLC_REMAP_ENCODINGS) and dst_has_scope_th
        translations.append(
            EncodingTranslation(
                src_enc_name=se,
                dst_enc_name=de,
                src_struct=_struct_name(se),
                dst_struct=_struct_name(de),
                src_bit_cnt=src_enc.bit_cnt,
                dst_bit_cnt=dst_enc.bit_cnt,
                mappings=_classify_fields(
                    src_enc,
                    dst_enc,
                    se,
                    has_coherency_remap=has_coherency_remap,
                    has_glc_remap=has_glc_remap,
                ),
                has_coherency_remap=has_coherency_remap,
                has_glc_remap=has_glc_remap,
                src_dt_index=src_dts.get(se, 0),
                src_enc_field_bit_cnt=src_enc.enc_field_bit_cnt,
                dst_enc_field_val=dst_evs.get(de, 0),
                # Keep this predicate identical to gen_instruction_builders:
                # only concrete encodings with their own instruction list get
                # a builder. Alternate decoder-only formats need condition-aware
                # construction before they can safely use this path.
                dst_has_builder=bool(dst_enc.insts),
            )
        )
    translations.sort(key=lambda t: (t.src_bit_cnt, t.src_enc_name))

    src_ns = f'rocjitsu::{src_name}'
    dst_ns = f'rocjitsu::{dst_name}'

    # Emit per-pair decode/encode/dispatch (encoding_fields.h generated separately)
    pair_lines = [
        _COPYRIGHT,
        '',
        '#pragma once',
        '',
        '#include <array>',
        '#include <bit>',
        '#include <cstdint>',
        '#include <cstring>',
        '',
        f'#include "{config.generated_include(src_name, "machine_insts.h")}"',
        f'#include "{config.generated_include(dst_name, "builders.h")}"',
        f'#include "{config.generated_include(dst_name, "machine_insts.h")}"',
        '#include "rocjitsu/code/dbt/encoding_translator.h"',
        '#include "encoding_fields.h"',
        '',
        'namespace rocjitsu {',
        '// Per-pair named namespace. Two pairs that share a source ISA',
        '// (e.g. cdna4->rdna3 and cdna4->rdna4) both emit decode_*_cdna4',
        '// helpers; isolating them per pair avoids ODR conflicts when',
        '// both headers are included in the same TU.',
        f'namespace {src_name}_to_{dst_name} {{',
        '',
    ]

    for t in translations:
        pair_lines.extend(_emit_decode_fn(t, src_ns, src_name))
    for t in translations:
        pair_lines.extend(_emit_encode_fn(t, dst_ns, dst_name))
    pair_lines.extend(
        _emit_dispatch(translations, src_name, dst_name, src_spec, dst_spec)
    )

    pair_lines += [
        f'}}  // namespace {src_name}_to_{dst_name}',
        '}  // namespace rocjitsu',
        '',
    ]

    pair_path = output_dir / f'encoding_{src_name}_to_{dst_name}.h'
    pair_path.write_text('\n'.join(pair_lines))
    _clang_format(pair_path)

    print(
        f'Generated {len(translations)} encoding translators for '
        f'{src_name} -> {dst_name}',
        file=sys.stderr,
    )
    print(f'  Header: {pair_path}', file=sys.stderr)
    if skipped:
        print(f'  Skipped: {len(skipped)} encodings', file=sys.stderr)
    return [str(pair_path)]
